def logo():
    import turtle
    turtle.width(3)
    turtle.bgcolor("yellow")
    turtle.speed(100)
    turtle.left(60)
    turtle.forward(80)
    turtle.left(90)
    turtle.forward(100)
    turtle.right(90)
    for i in range(23):
        turtle.right(3)
        turtle.forward(0.5)
    turtle.forward(70)
    turtle.left(70)
    turtle.forward(24)
    turtle.right(90)
    turtle.forward(15)
    turtle.right(89)
    turtle.forward(20)
    turtle.left(110)
    turtle.forward(13.5)
    turtle.left(70)
    turtle.forward(40)
    for i in range(30):
        turtle.right(1)
        turtle.forward(1)
    for i in range(30):
        turtle.right(4)
        turtle.forward(0.5)        
    for i in range(25):
        turtle.right(1.15)
        turtle.forward(0.80)
    turtle.forward(50)
    turtle.left(62)
    turtle.forward(13.5)
    turtle.left(115)
    turtle.forward(20)
    turtle.right(89)
    turtle.forward(15)
    turtle.right(90)
    turtle.forward(24)
    turtle.left(70)
    turtle.forward(40)
    for i in range(33):
        turtle.right(0.75)
        turtle.forward(1.25)
    turtle.forward(0.25)
    turtle.right(137)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(80)
    turtle.left(90)
    for i in range(33):
        turtle.forward(1.5)
        turtle.right(1.43)
    turtle.right(45)
    turtle.forward(5)
    turtle.right(90)
    turtle.forward(50.4)
    turtle.left(90)
    for i in range(10):
        turtle.forward(0.75)
        turtle.right(3)
    for i in range(10):
        turtle.right(9)
        turtle.forward(0.80)
    for i in range(25):
        turtle.right(1.5)
        turtle.forward(0.20)
    for i in range(25):
        turtle.right(1.15)
        turtle.forward(0.20)
    turtle.left(97)
    turtle.forward(50.4)
    turtle.right(90)
    turtle.forward(5)
    turtle.right(50)
    for i in range(33):
        turtle.right(1.15)
        turtle.forward(1.4)
    turtle.left(90)
    turtle.forward(80)
logo()
from tkinter import *
root=Tk()
root.title("FLIGHT BOOKING")
root.geometry("250x170")
root.configure(bg='#3388FF') 
l=Label(root,text="                              WELCOME TO BRAHMANDAM BOOKINGS !                                                       ",bg='#3388FF',fg='white',font="italic")
l.grid(row=0,column=3)
lf=Label(root,text="",bg='#3388FF')
lf.grid(row=1,column=1)
lff=Label(root,text="",bg='#3388FF')
lff.grid(row=2,column=0)
l1=Label(root,text="1. enter the number of passengers   : ",padx=50)
l1.grid(row=2,column=1)
entrypasno=Entry(root,width=40,fg='black')
entrypasno.grid(row=2,column=3)
global pasc
pasc=entrypasno.get()
lfff=Label(root,text="",bg='#3388FF')
lfff.grid(row=3,column=0)
l2=Label(root,text="2.        enter the FROM city                : ",padx=50)
l2.grid(row=4,column=1)
lfff=Label(root,text="",bg='#3388FF')
lfff.grid(row=4,column=0)
entryfromcity=Entry(root,width=40,fg='black')
entryfromcity.grid(row=4,column=3)
global frmcityy
frmcityy=entryfromcity.get()
lffff=Label(root,text="",bg='#3388FF')
lffff.grid(row=5,column=0)
entrydestcity=Label(root,text="3.    enter the DESTINATION city       :  ",padx=50)
entrydestcity.grid(row=6,column=1)
e3=Entry(root,width=40,fg='black')
e3.grid(row=6,column=3)
global destcityy
destcityy=e3.get()
lfffff=Label(root,text="",bg='#3388FF')
lfffff.grid(row=7,column=0)
entryclass=Label(root,text="4.    enter the CLASS                          :  ",padx=50)
entryclass.grid(row=8,column=1)
e4=Entry(root,width=40,fg='black')
e4.grid(row=8,column=3)
lffffff=Label(root,text="",bg='#3388FF')
lffffff.grid(row=9,column=0)
def qrc():
    import pyqrcode
    import png
    from pyqrcode import QRCode
    s =' TRANSACTION IS DONE SUCCESSFULLY!  THANKS FOR CHOOSING BRAHMANDAM BOOKINGS! GOOD DAY!  '
    url = pyqrcode.create(s)
    url.svg("myqr.svg", scale = 8)
    url.png('myqr.png', scale = 6)
def nenew():
    root2=Tk()
    root2.title("AIRLINES AND PAYMENT")
    root2.geometry("250x170")
    root2.configure(bg='#A52A2A')
    fakk34=Label(root2,text="",bg='#A52A2A')
    fakk34.grid(row=1,column=0)
    tto=Label(root2,text="  TO ",bg='#A52A2A')
    tto.grid(row=4,column=2)
    ewe1=Entry(root2,width=40,fg='black')
    ewe1.grid(row=4,column=1)
    ewe2=Entry(root2,width=40,fg='black')
    ewe2.grid(row=4,column=3)
    eff=Label(root2,text=" TOTAL SUMMARY  ",bg='#A52A2A')
    eff.grid(row=2,column=2)
    fakk345=Label(root2,text="",bg='#A52A2A')
    fakk345.grid(row=3,column=0)
    global frmcityy
    frmcityy=entryfromcity.get()
    ewe1.insert(0,frmcityy)
    global destcityy
    destcityy=e3.get()
    ewe2.insert(0,destcityy)
    fakk3456=Label(root2,text="",bg='#A52A2A')
    fakk3456.grid(row=5,column=0)
    airl=Label(root2,text="  AIRLINES   ",bg='#A52A2A')
    airl.grid(row=6,column=2)
    indi=Entry(root2,width=40,fg='black')
    indi.grid(row=6,column=1)
    indi.insert(0," INDIGO ")
    indin=Entry(root2,width=40,fg='black')
    indin.grid(row=6,column=3)
    indin.insert(0," 6E-527")
    fakk34567=Label(root2,text="",bg='#A52A2A')
    fakk34567.grid(row=7,column=0)
    times=Label(root2,text="  →    →   ",bg='#A52A2A')
    times.grid(row=8,column=2)
    t1=Entry(root2,width=40,fg='black')
    t1.grid(row=8,column=1)
    t1.insert(0," 16: 02 ")
    t2=Entry(root2,width=40,fg='black')
    t2.grid(row=8,column=3)
    t2.insert(0," 17: 27")
    fakk345678=Label(root2,text="",bg='#A52A2A')
    fakk345678.grid(row=9,column=0)
    fare=Label(root2,text="  TOTAL FARE   ",bg='#A52A2A')
    fare.grid(row=10,column=2)
    cou=Entry(root2,width=40,fg='black')
    cou.grid(row=10,column=1)
    global pasc
    pasc=entrypasno.get()
    cou.insert(0,pasc +" " +"people  (1200 each) ")
    bille=Entry(root2,width=40,fg='black')
    bille.grid(row=10,column=3)
    bille.insert(0,int(pasc)*1200)
    fakk3456789=Label(root2,text="",bg='#A52A2A')
    fakk3456789.grid(row=11,column=0)
    qrp=Button(root2,text= " headover to payment ",padx=27,pady=10,command=qrc)
    qrp.grid(row=12,column=2)    
def nextw():
    root1=Tk()
    root1.title("DETAILS SECTION")
    root1.geometry("250x170")
    root1.configure(bg='#90EE90')
    hea=Label(root1,text="                      ENTER YOUR TRAVEL DETAILS            ",bg='#90EE90')
    hea.grid(row=0,column=2)
    fak=Label(root1,text="",bg='#90EE90')
    fak.grid(row=1,column=0)
    names=Label(root1,text=" enter the passenger names     (traveller1,traveller2) :   ",padx=50)
    names.grid(row=2,column=1)
    fak2=Label(root1,text="",bg='#90EE90')
    fak2.grid(row=3,column=0)
    ages=Label(root1,text="                     enter the age of all passengers               :  ",padx=50)
    ages.grid(row=4,column=1)
    fak3=Label(root1,text="",bg='#90EE90')
    fak3.grid(row=5,column=0)
    gender=Label(root1,text="                enter the gender of all passengers             :  ",padx=50)
    gender.grid(row=6,column=1)
    entrypn=Entry(root1,width=40,fg='black')
    entrypn.grid(row=2,column=3)
    entryage=Entry(root1,width=40,fg='black')
    entryage.grid(row=4,column=3)
    entrygen=Entry(root1,width=40,fg='black')
    entrygen.grid(row=6,column=3)
    fak4=Label(root1,text="",bg='#90EE90')
    fak4.grid(row=7,column=0)
    bill=Button(root1,text="  generate my fare estimation   ",padx=27,pady=10,command=nenew)
    bill.grid(row=8,column=2)    
check=Button(root,text=" LOOK FOR FLIGHTS  ",padx=27,pady=10,command=nextw)
check.grid(row=10,column=3)
